---
# This playbooks configured existing openshift cluster to use internal Hawkular
# Pre-reqs:
#  Some kind of block storage class is available

- name: Configure invetory groups
  hosts: all:!controller:!bastion
  tasks:
    - set_fact:
        openshift_metrics_install_metrics: "{{ postdeploy_openshift_metrics_install_metrics }}"
        openshift_hosted_metrics_deploy: "{{ postdeploy_openshift_hosted_metrics_deploy }}"

- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-metrics/config.yml
