---
# This playbooks configures an existing openshift cluster to use glusterfs CRS as backed storage for the registry
# Pre-reqs:
# Glusterfs/CRS/CNS cluster already deployed 
# Registry already deployed

- name: Configure invetory groups
  hosts: all:!control_node:!bastion
  tasks:
    - set_fact:
        openshift_hosted_registry_storage_kind: glusterfs
        openshift_storage_glusterfs_heketi_is_native: "{{ override_openshift_storage_glusterfs_heketi_is_native }}"
        openshift_storage_glusterfs_heketi_topology_load: "{{ override_glusterfs_heketi_topology_load }}"
        openshift_storage_glusterfs_storageclass: "{{ override_openshift_storage_glusterfs_storageclass }}"
        openshift_storage_glusterfs_block_storageclass: "{{ override_glusterfs_block_storageclass }}"
    - name: Add glusterfs nodes to glusterfs group for playbooks
      add_host:
        name: "{{ item }}"
        groups: glusterfs
      with_items:
      - "{{ groups['override_glusterfs'] }}"

- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/init/main.yml
- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-glusterfs/config.yml
- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-hosted/config.yml
...
